# Generated by Django 6.0.3 on 2026-06-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-PESA'), ('card', 'Card'), ('manual', 'Manual (Send Money)')], max_length=10),
        ),
    ]
