# Generated by Django 6.0.3 on 2026-06-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
